-- MySQL Script generated by MySQL Workbench
-- Mon May  6 13:04:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Estado` (
  `idEstado` INT NOT NULL,
  `Activo` VARCHAR(45) NOT NULL,
  `Inactivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuarios` (
  `id` INT NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `rol` INT(11) NOT NULL,
  `Estado` VARCHAR(50) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`id`, `Estado_idEstado`),
  CONSTRAINT `fk_usuarios_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `proyecto`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usuarios_Estado1_idx` ON `proyecto`.`usuarios` (`Estado_idEstado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto`.`SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`SERVICIO` (
  `id_SERVICIO` INT NOT NULL AUTO_INCREMENT,
  `Ubicacion_actual` VARCHAR(250) NOT NULL,
  `Ubicacion_Destino` VARCHAR(250) NOT NULL,
  `Can_Personas` VARCHAR(45) NULL,
  `Can_Motos` VARCHAR(45) NULL,
  `Metodo_Pago` VARCHAR(45) NULL,
  `Id_Cliente` DATE NOT NULL,
  `ValorT` FLOAT NOT NULL,
  `Fecha` DATE NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id_SERVICIO`, `usuarios_id`),
  CONSTRAINT `fk_SERVICIO_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `proyecto`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SERVICIO_usuarios1_idx` ON `proyecto`.`SERVICIO` (`usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto`.`Mototaxista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Mototaxista` (
  `id_Mototaxista` INT NOT NULL,
  `Marca` DATE NOT NULL,
  `Placa` DATE NOT NULL,
  `Modelo` DATE NOT NULL,
  `Color` REAL NOT NULL,
  `Tarjeta_de_propiedad` LONGBLOB NOT NULL,
  `Soat` LONGBLOB NOT NULL,
  `Tecno_mecanica` LONGBLOB NOT NULL,
  `Licencia_de_conducir` LONGBLOB NULL,
  `SERVICIO_id_SERVICIO` INT NOT NULL,
  `SERVICIO_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id_Mototaxista`, `SERVICIO_id_SERVICIO`, `SERVICIO_usuarios_id`),
  CONSTRAINT `fk_Mototaxista_SERVICIO1`
    FOREIGN KEY (`SERVICIO_id_SERVICIO` , `SERVICIO_usuarios_id`)
    REFERENCES `proyecto`.`SERVICIO` (`id_SERVICIO` , `usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mototaxista_SERVICIO1_idx` ON `proyecto`.`Mototaxista` (`SERVICIO_id_SERVICIO` ASC, `SERVICIO_usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto`.`PAGO_DEL_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`PAGO_DEL_SERVICIO` (
  `id_PAGO_DEL_SERVICIO` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Metodo_Pago` VARCHAR(45) NOT NULL,
  `Nombres_del_cliente` VARCHAR(450) NOT NULL,
  `Nombres_del_mototaxista` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id_PAGO_DEL_SERVICIO`, `usuarios_id`),
  CONSTRAINT `fk_PAGO_DEL_SERVICIO_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `proyecto`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PAGO_DEL_SERVICIO_usuarios1_idx` ON `proyecto`.`PAGO_DEL_SERVICIO` (`usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto`.`Servicios Solicitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Servicios Solicitados` (
  `idServicios Solicitados` INT NOT NULL,
  `cantidad_de_solicitud` SMALLINT NOT NULL,
  `puntuacion` SMALLINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `usuarios_Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idServicios Solicitados`, `usuarios_id`, `usuarios_Estado_idEstado`),
  CONSTRAINT `fk_Servicios Solicitados_usuarios1`
    FOREIGN KEY (`usuarios_id` , `usuarios_Estado_idEstado`)
    REFERENCES `proyecto`.`usuarios` (`id` , `Estado_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Servicios Solicitados_usuarios1_idx` ON `proyecto`.`Servicios Solicitados` (`usuarios_id` ASC, `usuarios_Estado_idEstado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto`.`Servicios aceptados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Servicios aceptados` (
  `cantidad` SMALLINT NULL,
  `Servicios aceptadoscol` VARCHAR(45) NULL,
  `puntuacion` SMALLINT NOT NULL,
  `Mototaxista_id_Mototaxista` INT NOT NULL,
  `Mototaxista_SERVICIO_id_SERVICIO` INT NOT NULL,
  `Mototaxista_SERVICIO_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`Mototaxista_id_Mototaxista`, `Mototaxista_SERVICIO_id_SERVICIO`, `Mototaxista_SERVICIO_usuarios_id`),
  CONSTRAINT `fk_Servicios aceptados_Mototaxista1`
    FOREIGN KEY (`Mototaxista_id_Mototaxista` , `Mototaxista_SERVICIO_id_SERVICIO` , `Mototaxista_SERVICIO_usuarios_id`)
    REFERENCES `proyecto`.`Mototaxista` (`id_Mototaxista` , `SERVICIO_id_SERVICIO` , `SERVICIO_usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
